spring.application.name=carrito

# Ajustes de conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/tiendaonline
spring.datasource.username=jairo
spring.datasource.password=

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true

# Persistencia de la información de sesiones
# Source - https://stackoverflow.com/q/78398910
# Posted by Rolch2015, modified by community. See post 'Timeline' for change history
# Retrieved 2026-02-25, License - CC BY-SA 4.0
server.servlet.session.persistent=true
server.servlet.session.store-dir=sessions
